### PR TITLE
Added option to choose filename when exporting lab script, lab zip fi…

### PR DESCRIPTION
**Pull request by NogyJ0D**
…le, and lab configuration.

### CODE REVIEW

**Comment by lorenzo93** [comment]
Hi @NogyJ0D ,

I'm sorry for replying so late :)

I was trying your code but I'm not able to test the change. Are you sure that the elements you inserted are compatible with Electron?

**Comment by lorenzo93** [comment]
Hi @NogyJ0D ,

I'm sorry for the late reply :)
I've tried your code and see the before and after behaviour.
Using your forms it just adds another step to save the file, but the filename could already be set before downloading. You just need to set your browser to ask each time where to save files.
In my environment with this option this is the procedure:

1. Set the file name
image
2. Specify where to save the file, and again (if needed) change the filename
image

An alternative idea would be to take the default filename from the Lab Description field (if set).
What do you think about?

**Comment by NogyJ0D** [comment]
Hello @lorenzo93, thanks for trying it out.

The behavior is already built so that if you don't type in a file name, the default file is called "netkit.script", "lab.zip" or "netkit.config"; depending on what you download.

Maybe what I could do is already leave the name "netkit" or "lab" in the text field. Writing a file name is completely optional.

**Comment by lorenzo93** [comment]
Hi @NogyJ0D ,

do you use NLG from the sources via browser or you downloaded the release and use the electron app?

**Comment by NogyJ0D** [comment]
I use it cloned from this repository with the browser

**Comment by lorenzo93** [comment]
That's why you're experiencing this problem.
Please, download the compiled release and try it from there. It will ask for the file name each time :)

**Comment by NogyJ0D** [comment]
Sorry for the delay. Now I understand what you are saying, in that case this is no longer useful.

**Pull request closed without merging**
