### PR TITLE
lab generator update

### PR DESCRIPTION
**Pull request by giovanni-grieco**
Attempted to convert make.js for it to create frr.conf files. 

Tested with rip and ospf (both running on the same router too) and it all seems to work. 

(OLD)Unaware if it works well with bgp (I haven't properly studied it yet).

Known issues
- Whenever a routing procotol is selected for a certain router, you can add custom commands to the .conf file. The problem being that previously you had a .conf for every selected protocol and you have a text box allowing you to put custom commands for every single configuration file, while now everything is put together in a single frr.conf and so you should have a single custom commands text box but currently, this isn't the case.
- Can't remove the "ip" in front of "ospf cost <cost value>". I couldn't find which function is responsible for adding "ip" in front. It shouldn't be a big issue if it remains there anyways.

I hope this is a good starting point.

-EDIT 1:
Added frontend options to switch between quagga and frr, check below.

-EDIT 2:
Updated DNS to new standard (and I may have fixed a legacy bug)

-EDIT 3:
Restored text boxes for frr configurations to allow users to put in custom commands after a specific routing protocol section. Works well for BGP as far as I tested it.

-EDIT 4:
DNS works, all routing protocol seem to work.

### CODE REVIEW

**Comment by giovanni-grieco** [comment]
Added the option for the user to select which routing software to use (quagga or frr). 
Frr
immagine
Quagga
immagine

Generated labs
immagine

**Comment by giovanni-grieco** [comment]
New layout

With frr selected
immagine

with Quagga selected
immagine

Now, the image gets set in the lab.conf depending on the routing software
immagine

**Comment by lorenzo93** [comment]
Hi @giovanni-grieco,

I'm making some small bug-fixes and libraries upgrades in the `develop` branch.
I've changed your merge target to this branch so your PR will be included in next release, please pull the new changes since there are now conflicting files 😄

**Comment by giovanni-grieco** [comment]
Implementati nuovi text box per comandi custom

immagine
immagine

**Comment by lorenzo93** [comment]
Hi @giovanni-grieco ,

do you think your developing is finished and tested? can I merge this branch into the main and release a new verision?

**Comment by giovanni-grieco** [comment]
> Hi @giovanni-grieco ,
> 
> do you think your developing is finished and tested? can I merge this branch into the main and release a new verision?

I've tested the lab generator recreating [this topology](https://github.com/KatharaFramework/Kathara-Labs/blob/main/main-labs/labs-integrating-several-technologies/bgp-ospf-rip-interplay/kathara-lab_bgp-ospf-rip.pdf) with slight modifications to involve DNS with a certain depth of domains (for example, down to ".dia.dia.uniroma3.it.", a client and a couple of webservers.

It all seems to work :)

Below you can find the generated lab that I tested.
[testlab.zip](https://github.com/KatharaFramework/Netkit-Lab-Generator/files/14027037/testlab.zip)

**Pull request merged**
